# Generated by Django 4.0.4 on 2022-05-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_contactmodel_reportlinkmodel_alter_urlmodels_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UrlModels',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='contact_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reportlinkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportlinkmodel',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
