# Generated by Django 4.0.4 on 2022-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_urlmodel_delete_urlmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='contact_created_at',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yuborilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='reportlinkmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yuborilgan vaqti'),
        ),
    ]
