# Generated by Django 4.0.4 on 2022-05-22 08:12

from django.db import migrations, models
import url.models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_remove_contactmodel_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlinkmodel',
            name='url',
            field=models.URLField(max_length=300, validators=[url.models.validate_url]),
        ),
    ]
